version: "3.8"
services:
  nitter:
    image: zedeus/nitter:latest
    restart: unless-stopped
    ports:
      - 8080
    volumes:
      - nitter-config:/src/nitter.conf:ro
      - nitter-sessions:/src/sessions.jsonl:ro
      - nitter-data:/data
    depends_on:
      - nitter-redis
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:8080/Jack/status/20 || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    user: "998:998"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  nitter-redis:
    image: redis:6-alpine
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - nitter-redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 2
    user: "999:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  nitter-config:
  nitter-sessions:
  nitter-data:
  nitter-redis:
