version: "3.8"

services:
  mysql:
    image: mysql:8.0.32
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command:
      - "mysqld"
      - "--default-authentication-plugin=mysql_native_password"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--character-set-server=utf8mb4"
    networks:
      - dokploy-network

  redis:
    image: redis:7.0.7
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - dokploy-network

  gumroad-app:
    image: antiwork/gumroad:latest
    restart: unless-stopped
    ports:
      - "${PORT}:3000"
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis:6379/0
      - SIDEKIQ_REDIS_HOST=redis:6379/1
      - RAILS_ENV=production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DEVISE_SECRET_KEY=${DEVISE_SECRET_KEY}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - S3_BUCKET=${S3_BUCKET}
    networks:
      - dokploy-network
    volumes:
      - app_storage:/app/storage

networks:
  dokploy-network:
    external: true

volumes:
  mysql_data:
  redis_data:
  app_storage:
