version: "3.8"
services:
  client:
    build: .
    environment:
      - BASE_URL=http://server:3000
    ports:
      - 8080
    command: ["npm", "run", "client:dev"]
    depends_on:
      - server
  server:
    build: .
    ports:
      - 3000
    environment:
      - NODE_DB_URI=mongodb://mongo/habitrpg
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6
    ports:
      - 27017
volumes:
  mongo-data: {}
