services:
  opengist:
    image: ghcr.io/thomiceli/opengist:1.10
    restart: unless-stopped
    ports:
      - "6157:6157" # HTTP port
      - "2222" # SSH port, can be removed if you don't use SSH
    volumes:
      - "$HOME/.opengist:/opengist"
    environment:
